version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./server/tests/WebTests/WebTests.csproj

  build:
    commands:
      - echo Test started on `date`
      - dotnet test ./server/tests/WebTests/WebTests.csproj
