version: "3.9"

services:
  db:
    container_name: db
    image: postgres:12
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DOCKER_POSTGRES_DB}
      - POSTGRES_USER=${DOCKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
    networks:
      - grubhub

volumes:
  db:
