version: "3.9"

services:
  web:
    container_name: web
    build: .
    image: jlwalkerlg/grubhub:latest
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: ${DOCKER_ASPNETCORE_ENVIRONMENT}
    networks:
      - grubhub

  redis:
    container_name: redis
    image: redis:6.2.2
    ports:
      - 6379:6379
    networks:
      - grubhub

networks:
  grubhub:
