version: "3.9"

services:
  web:
    container_name: web
    build: .
    image: jlwalkerlg/grubhub:latest
    ports:
      - 5000:5000
    depends_on:
      - redis
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: ${DOCKER_ASPNETCORE_ENVIRONMENT}
    networks:
      - grubhub

  redis:
    container_name: redis
    image: redis:6.2.2
    ports:
      - 6379:6379
    networks:
      - grubhub

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${DOCKER_RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${DOCKER_RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    networks:
      - grubhub

  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    volumes:
      - es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - grubhub

  kib01:
    container_name: kib01
    image: docker.elastic.co/kibana/kibana:7.12.1
    depends_on:
      - es01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    networks:
      - grubhub

  seq:
    container_name: seq
    image: datalust/seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${DOCKER_SEQ_FIRSTRUN_ADMINPASSWORDHASH}
    volumes:
      - seq:/data
    ports:
      - 8081:80
      - 5341:5341
    networks:
      - grubhub

volumes:
  rabbitmq:
  es01:
  seq:

networks:
  grubhub:
